export const COS_ENDPOINT = process.env.COS_ENDPOINT || null;
export const COS_APIKEY = process.env.COS_APIKEY || null;
export const COS_SERVICEINSTANCE = process.env.COS_SERVICEINSTANCE || null;
export const COS_REGION = process.env.COS_REGION || 'us-south' ;
export const COS_BUCKET = process.env.COS_BUCKET || null ;
export const COS_READ_ENDPOINT = process.env.COS_READ_ENDPOINT || null;
export const S3_READ_URL_PREFIX = process.env.S3_READ_URL_PREFIX || null;
export const S3_IMAGE_KEY_PREFIX = process.env.S3_IMAGE_KEY_PREFIX || null;
export const S3_VIDEO_KEY_PREFIX = process.env.S3_VIDEO_KEY_PREFIX || null;
